version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: my_pass_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4815162342
    ports:
      - "3306:3306"
    volumes:
      - "./volumes:/home/dumps"

volumes:
  mysql:
    external: true
